service: forex-slack-bot

frameworkVersion: "<=1.9.0"

custom:
  namespace: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  environment:
    CLIENT_ID: ENV["SLACK_CLIENT_ID"]
    CLIENT_SECRET: ENV["SLACK_CLIENT_SECRET"]
    INSTALL_SUCCESS_URL: your_url.com/#success
    INSTALL_ERROR_URL: your_url.com/#fail
    VERIFICATION_TOKEN: ENV["SLACK_VERIFICATION_TOKEN"]
    NAMESPACE: ${self:custom.namespace}
    TEAMS_TABLE: ${self:custom.namespace}-teams

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.TEAMS_TABLE}
    - Effect: Allow
      Action:
        - lambda:invokeFunction
      Resource:
        - arn:aws:lambda:*:*:function:${self:custom.namespace}-actions
functions:

  actions:
    handler: actions.handler

  events:
    handler: events.handler
    events:
      - http:
          path: events
          method: post

  install:
    handler: install.handler
    events:
      - http:
          path: install
          method: get
  hello:
    handler: handler.hello

resources:
  Resources:
    TeamsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEAMS_TABLE}
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
